settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: baohuo1
    name: cf定阅链接
    description: 'Built for anything connected to the Internet.'
    url: 'https://cf.999.cloudns.be/4a34d8b6-9144-45a8-aa16-9afe56f44ea7'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: baohuo2
    name: cf订阅链接
    description: 'Built for anything connected to the Internet.'
    url: 'https://cf.666.cloudns.be/4a34d8b6-9144-45a8-aa16-9afe56f44ea7'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: baohuo3
    name: cf定阅链接
    description: 'Built for anything connected to the Internet.'
    url: 'https://cf.atybz.cloudns.be/4a34d8b6-9144-45a8-aa16-9afe56f44ea7'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: baohuo4
    name: cf订阅链接
    description: 'Built for anything connected to the Internet.'
    url: 'https://cf.mix.cloudns.be/4a34d8b6-9144-45a8-aa16-9afe56f44ea7'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true    
  
  - id: baohuo5
    name: cf订阅链接
    description: 'Built for anything connected to the Internet.'
    url: 'https://cf.88888.ip-ddns.com/4a34d8b6-9144-45a8-aa16-9afe56f44ea7'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true    
  
  - id: baohuo6
    name: 机场签到
    description: 'Built for anything connected to the Internet.'
    url: 'https://jcqd.999.cloudns.be/11778378'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true    
    
  - id: baohuo7
    name: serv00-s2网页进程保活
    description: 'Built for anything connected to the Internet.'
    url: 'https://mcwk.serv00.net/info/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true    

  - id: baohuo8
    name: serv00-s3-at网页进程保活
    description: 'Built for anything connected to the Internet.'
    url: 'https://atybz.serv00.net/info/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true    

  - id: baohuo9
    name: serv00-s3-okj网页进程保活
    description: 'Built for anything connected to the Internet.'
    url: 'https://okjhy.serv00.net/info/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true    
    
  - id: baohuo10
    name: serv00-s3-oku网页进程保活
    description: 'Built for anything connected to the Internet.'
    url: 'https://okuyt.serv00.net/info/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true    
    
  - id: baohuo11
    name: serv00-s16-mc网页进程保活
    description: 'Built for anything connected to the Internet.'
    url: 'https://mcwkatybz.serv00.net/info/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true    

  - id: baohuo12
    name: serv00-16-wl网页进程保活
    description: 'Built for anything connected to the Internet.'
    url: 'https://wlsxnz.serv00.net/info/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true    
