settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: baohuo1 # unique identifier
    name: baohuo
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://baohuo.999.cloudns.be/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: baohuo2 # unique identifier
    name: baohuo
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://baohuo.666.cloudns.be/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: baohuo3
    name: baohuo
    description: 'Built for anything connected to the Internet.'
    url: 'https://baohuo.atybz.cloudns.be/11f1050f-a4e9-4d2c-bb9c-8521a9bddf0a'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: baohuo4
    name: 域名保活
    description: 'Built for anything connected to the Internet.'
    url: 'https://baohuo.mix.cloudns.be/11f1050f-a4e9-4d2c-bb9c-8521a9bddf0a'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true


    
